---
title: "Untitled"
author: "Eudald"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(dplyr)
library(readr)
library(ggtern)
library(extrafont) 
loadfonts(device = "win")
par(family = "Helvetica")
theme_set(theme_bw())
```

```{r}
df <- read_csv("output/theta.csv") |> 
  select(-c(`...1`, entropy))
```

```{r}
change_labels <- function(x) as.numeric(x) / 100
```


```{r}
base_col <- "#440154FF"
df |>
  # rename(High = I, Low = II, Average = III) |> 
  ggtern(aes(II, I, III)) +
  geom_hex_tern(
    size = .5,
    colour = base_col,
    bins = 12,
    fun = \(x) log(sum(x)),
    show.legend = T
  ) +
  scale_fill_continuous(type = "viridis") +
  scale_T_continuous(labels = c(0, 0.2, .4, .6, .8, 1)) +
  scale_R_continuous(labels = c(0, 0.2, .4, .6, .8, 1)) +
  scale_L_continuous(labels = c(0, 0.2, .4, .6, .8, 1)) +
  theme_custom(
    tern.panel.background = base_col, 
    col.grid.minor = base_col
    ) + 
  labs(fill = "Log probability \ndensity") + 
  theme(
    legend.position = c(.85,.75),
    text = element_text(family = "Helvetica", size = 16)
  )
ggsave("plots/ternary.pdf", width=7,height=7, dpi = 300)
```
