data:
  train: "u1.base"
  test: "u1.test"

training:
  iterations: 400
  sampling: 5
  seed: 1714

optimizer:
  debug: false
  study_name: mmsbm
  trials: 1
  min_user_groups: 3
  max_user_groups: 3
  min_item_groups: 3
  max_item_groups: 3